export * from './Tarjetas.types'
export * from './ServicioPagos.types'
export * from './Bancos.types'
export * from './NroComercio.types'
export * from './PlanPago.types'
export * from './PlanDestacadoGeneral.types'
export * from './PlanDestacadoCard.types'